//
// Created by denis on 02.08.2022.
//

#ifndef COURSEWORKDB_COMMONUSERWINDOWSFACTORY_H
#define COURSEWORKDB_COMMONUSERWINDOWSFACTORY_H


class CommonUserWindowsFactory {

};


#endif //COURSEWORKDB_COMMONUSERWINDOWSFACTORY_H
